#!/bin/bash

set -o errexit
set -o nounset

airflow db init
airflow db migrate
airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin
